name: Deploy webwatch Application

on:
  release:
    types: [prereleased, edited]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile webwatch.py

    - name: Add files to dist/
      run: |
        mkdir dist/config
        cp config/example_config.json dist/config/example_config.json

    - name: Zip the application
      run: zip -r webwatch.zip dist/

    - name: Upload to GitHub Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WEBWATCH_RELEASE_DEPLOYMENT }}
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./webwatch.zip