name: Deploy webwatch Application

on: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: pyinstaller --onefile webwatch.py

    - name: Add files to dist/
      run: |
        mkdir dist/config
        cp dist/config/example_config.json dist/config/example_config.json

    - name: Zip the application
      run: zip -r webwatch.zip dist/

    - name: Upload to GitHub Releases
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./webwatch.zip
        asset_name: webwatch.zip
        asset_content_type: application/zip
